apiVersion: v1
kind: ConfigMap
metadata:
  name: trox-map
  namespace: kube-system
data:
  #IP address of the network tap
  ip: "ip_of_tap_here"
  #Type of tap. Currently only gigamon is supported
  tap_type: "gigamon"
  #app label of pods to watch
  #examples: 1 app: "app1"
  #          2 apps: "app1,app2"
  app_label: "bro"
  #Seconds to wait to see if pod is ready
  timeout: "300"
