apiVersion: apps/v1
kind: Deployment

metadata:
  name: troxileia
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troxileia
  template:
    metadata:
      name: troxileia
      labels:
        app: troxileia
    spec:
      containers:
      - name: troxileia
        imagePullPolicy: Always
        image: gcr.io/edcop-dev/mbaker:v1
      restartPolicy: Always
      dnsPolicy: ClusterFirst
